frontend:
    name: 'Wav2Vec2'
    args: {}
        
backbone:
    name: 'SENet'
    args:
        layers  : [3, 4, 6, 3]
        channels: [16, 16, 32, 64, 128]
    
pooling   : 'Attentive_Statistics_Pooling'
attn_heads: 8
duration  : 4.