exp_dir: './exp'
log_dir: './log'

train_dataset_args:
    data_dir  : 'data/track2adp'
    data_list : 'data/label/track2adp_list.txt'
    duration  : 4.
    mix       : True
    mix_ratio : [0.01, 0.3]
    hop_length: 128
    augment   : False
    # augment   : True
    # noise_dir : 'data/musan'
    # rir_dir   : 'data/simulated_rir_16k'

valid_dataset_args:
    data_dir : 'data/track2adp'
    data_list: 'data/label/track2adp_list.txt'

test_dataset_args:
    data_dir : 'data/track2adp'
    data_list: 'data/label/track2adp_list.txt'

eval_dataset_args:
    data_dir : 'data/track2test'

optim: {'name': 'Adam', 'args': {'lr': 0.001, 'weight_decay': 0.0001}}

monitor:
    valid/eer:
        mode: 'min'
    valid/cls_loss:
        mode: 'min'
save_best_only: True

patience : 10
min_epoch: 100
max_epoch: -1